#!/usr/bin/env python3
"""
convert_species_dict.py
-----------------------
Reads your lab's speciesDict.py and writes resources/speciesDict.json,
which InMemorySpeciesRepository.loadFromDict() consumes at app startup.

Usage
-----
  python scripts/convert_species_dict.py [--dict-path PATH_TO_SPECIESDICT]

  # Default: looks for speciesDict.py next to this script
  python scripts/convert_species_dict.py

  # Explicit path
  python scripts/convert_species_dict.py --dict-path /lab/data/speciesDict.py

The script imports speciesDict.py directly, so it must be importable
(i.e. it should not run side-effects at module level beyond dict definitions).

Required names inside speciesDict.py
-------------------------------------
  chinese_to_id   : { chinese_name  -> lab_id }
  id_to_chinese   : { lab_id        -> chinese_name }
  english_to_id   : { english_name  -> lab_id }
  id_to_english   : { lab_id        -> english_name }
  id_to_scientific: { lab_id        -> scientific_name }
  scientific_to_id: { scientific    -> lab_id }
  ebird_to_id     : { ebird_code    -> lab_id }
"""

import argparse
import importlib.util
import json
import os
import sys


def load_species_dict(dict_path: str) -> dict:
    """Dynamically import speciesDict.py and return its namespace."""
    spec = importlib.util.spec_from_file_location("speciesDict", dict_path)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def build_json(mod) -> dict:
    required = [
        "ebird_to_id",
        "id_to_chinese",
        "id_to_english",
        "id_to_scientific",
    ]
    missing = [r for r in required if not hasattr(mod, r)]
    if missing:
        sys.exit(f"[error] speciesDict.py is missing: {', '.join(missing)}")

    return {
        "_comment": [
            "Auto-generated by scripts/convert_species_dict.py",
            "Do NOT edit by hand — re-run the script instead.",
        ],
        "ebird_to_id":      mod.ebird_to_id,
        "id_to_chinese":    mod.id_to_chinese,
        "id_to_english":    mod.id_to_english,
        "id_to_scientific": mod.id_to_scientific,
    }


def main():
    parser = argparse.ArgumentParser(description="Convert speciesDict.py → speciesDict.json")
    parser.add_argument(
        "--dict-path",
        default=os.path.join(os.path.dirname(__file__), "speciesDict.py"),
        help="Path to speciesDict.py (default: next to this script)",
    )
    parser.add_argument(
        "--out",
        default=os.path.join(os.path.dirname(__file__), "..", "resources", "speciesDict.json"),
        help="Output JSON path (default: resources/speciesDict.json)",
    )
    args = parser.parse_args()

    dict_path = os.path.abspath(args.dict_path)
    out_path  = os.path.abspath(args.out)

    if not os.path.isfile(dict_path):
        sys.exit(f"[error] Cannot find speciesDict.py at: {dict_path}")

    print(f"[info] Loading  {dict_path}")
    mod    = load_species_dict(dict_path)
    result = build_json(mod)

    # Validate: every ebird_to_id value must appear in id_to_chinese
    unmapped = [
        code for code, lab_id in result["ebird_to_id"].items()
        if lab_id not in result["id_to_chinese"]
    ]
    if unmapped:
        print(f"[warn] {len(unmapped)} eBird code(s) map to a lab_id not in id_to_chinese:")
        for c in unmapped[:10]:
            print(f"       {c} → {result['ebird_to_id'][c]}")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(result, f, ensure_ascii=False, indent=2)

    n_species = len(result["id_to_chinese"])
    n_ebird   = len(result["ebird_to_id"])
    print(f"[ok]   Wrote {out_path}")
    print(f"       {n_species} lab species  •  {n_ebird} eBird code mappings")


if __name__ == "__main__":
    main()
